server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /liteflow-runtime
    application-display-name: liteflow-runtime


liteflow:
  monitor:
    enable-log: true #是否启用监控
    queue-limit: 20000 #监控队列的大小







