import {Metadata} from 'next'


const defaultMetadata: Metadata = {
    title: "ElasticBook ",
    keywords: "",
    description: 'Generated by create next app',
    icons: {

        icon: 'https://cdn.jansora.com/logo/orbit.svg',
        shortcut: '/shortcut-icon.png',
        apple: 'https://cdn.jansora.com/logo/orbit.svg',
        other: {
            rel: 'apple-touch-icon-precomposed',
            url: '/apple-touch-icon-precomposed.png',
        },
    }
}


export function metadata(_metadata: Metadata): Metadata {
    if (!_metadata) {
        return defaultMetadata
    }

    return {
        ...defaultMetadata,
        ..._metadata,
        title: `${_metadata.title} | ${defaultMetadata.title}`,
    }

}